# Generated by Django 3.1.2 on 2020-10-28 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='text_file',
            new_name='TextFile',
        ),
    ]
