# Generated by Django 3.1.2 on 2020-10-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_auto_20201031_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
