# Generated by Django 3.1.2 on 2020-10-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20201031_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
