# Generated by Django 3.1.2 on 2020-10-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0005_textfile_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
