# Generated by Django 3.1.2 on 2020-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0006_textfile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='security',
            field=models.TextField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC'),
        ),
    ]
